[package]
name = "hello-rust"
version = "0.1.0"
authors = ["IMOTO Yasuhiro <soyiharu@hotmail.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.3.1"
rand = "0.8.1"